### ISSUE TITLE
Dot.NXMOD is not working anymore.

### ISSUE THREAD

**Issue by m0jek** [em00k/NXMod-src#1]
I have a ZX Spectrum Next Issue 4 Model ( aka KS2)
I have noticed that .NXMOD some.mod does not work any more. The issue was noticed when I tried to open a MOD file using the browser, the screen display border go a solid colour and then nothing. I have to press reset button or power off.

Running from CLI has the same affect.

Some strings from the binary ....

```
NXMODdot1.2-9bitcolor+em00k

NXMOD - v1.2b by njoi 19/03/22
Plays Amiga Protracker Modules.
Amazing PAULA Emulation &
MOD Replayer by 9bitcolor
dotcode by em00
```

**Comment by em00k** [comment]
Hi
Can you give an example of the mods that do this? 
Thanks

**Comment by m0jek** [comment]
Thank you for getting back to me so quickly.

You can use any of the mods that are examples in **/apps/audio/NXModPlayer/mods** as supplied as part of the standard KS2 disk image, namely;

- AWESOME5.MOD
- Jarresque.mod
- KEF2.MOD
- dune_ecolove.mod

**NXModPlayer** plays them all just great, of course. 

I could have sworn it used to work, but I even booted up from a virgin KS2 distro Image and tried and had the same issue. Even  **CSpect** does the same.

On the SpecNext forum someone also posted, so I am not alone it seems.

https://www.specnext.com/forum/viewtopic.php?t=2493

Cosmic radiation ? 

Cheers.

**Comment by em00k** [comment]
They should most definietly work, however not in CSpect as it doesn't currenlty handle the CTC interrupt setup like HW. Could you run .CONFIG from the command line and report back:

Core
Video

The version of NextZXOS and FW that is reported on boot up. Can you also let me know where you are downloading the distro from? SpecNext website or gitlab? 

Thanks

**Comment by m0jek** [comment]
Here are the the values you asked for;

```
Core v3.02.00
Video 60 Hz HDMI

Firmware V1.4
```

The distro is what came with my Next. I backed up the SD Card before using so I do have a virgin image I have been using for testing. 

As an aside, I did run at 50 Hz ...

**Comment by m0jek** [comment]
Hah!
Your request for the video mode got me thinking.
When I first got my Next I plugged it into a **_VGA port of my TV_** ...

So, now just plugged it back into the telly VGA port ...

.NXMOD **now works** as expected!

I have been using the Next at my desk that has a fancy LG monitor, and I had forgotten that I had initially used the telly in the living room.

**Comment by em00k** [comment]
Ahh, that is good to hear! I can't think why NXModPlayer should work in VGA60Hz but not .nxmod - as they both use the same start up code but its always possible I may have screwed something up. Although having a quick scan through sources there's nothing that is obvious. 

It worth noting that there is a new version of the distro on gitlab (https://gitlab.com/thesmog358/tbblue) that includes a change on how the HDMI image is produced ; this is the version the players have been tested agaisnt, I would certainly recommend you upgrading, as that download will be pushed to the official distro fairly soon. Once installed test again in HDMI - when you select "DIGITAL" on the bootup the mode should be displayed "VGA7 - 50Hz or 60Hz"

:)

**Comment by m0jek** [comment]
I will give the update a go and report back before closing the ticket.

**Comment by m0jek** [comment]
Upgrading to 3.02.01 core from https://gitlab.com/thesmog358/tbblue  as per guide https://www.specnext.com/hdmi-for-ks2-machines/ worked a treat.

On my system and screen, I can now run .nxmod and other 50Hz VGA sensitive stuff on my HDMI screen. The sound is also perfect.

Thank you for the suggestion.
